# This workflow will build app image & deploy it on dockerhubs, and deploy app on Github pages. 

name: calculator web app CI/CD

on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

jobs:

  build-deploy:
    name: build and deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
  
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and Deploy Docker Image on dockerhub
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: matao39/calculator
        tags: ${{ secrets.CALCULATOR_TAG }} 
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    -  name: Deploy on Github pages
       uses: peaceiris/actions-gh-pages@v3
       with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
